### ISSUE TITLE
cleartext traffic?

### ISSUE THREAD

**Issue by IzzySoft** [RohitKushvaha01/Xed-Editor#181]
Returning from vacation and catching up with the backlog, I see the scanner here at IzzyOnDroid sent a warning:

```
! repo/com.rk.xededitor_33.apk declares flag(s): usesCleartextTraffic
```

Can you please clarify what cleartext (unencrypted HTTP) traffic is needed/used and where to? Thanks in advance!

**Comment by RohitKushvaha01** [comment]
> Returning from vacation and catching up with the backlog, I see the scanner here at IzzyOnDroid sent a warning:
> 
> ```
> ! repo/com.rk.xededitor_33.apk declares flag(s): usesCleartextTraffic
> ```
> 
> Can you please clarify what cleartext (unencrypted HTTP) traffic is needed/used and where to? Thanks in advance!

I use a local HTTP server to handle HTML or Markdown previews when the user requests them. I added the usesCleartextTraffic flag as a precaution, to ensure that these local HTTP connections would function properly, since I wasn't certain if Android would allow unencrypted traffic for local connections. No external or insecure internet traffic is involved.

**Comment by IzzySoft** [comment]
Thanks, fits! And yes, it is needed for local connections too. I didn't check if you use it already, but there's a network security config where you can pin `usesCleartextTraffic` to local connections (or any other servers), so no unencrypted remote connections are opened accidentally.
