### ISSUE TITLE
Undo, redo, or repeat an action

### ISSUE THREAD

**Issue by Pantyhose-X** [RohitKushvaha01/Xed-Editor#6]

**Comment by togeth3** [comment]
hi
we fin à few 'commands'  by using 
hacker's keyboard...
by ex ctrl z and y in order to change, and roll back
changes in text..

but nothing in order to save  changes or Format or...
???
is there some help? page? man?
where and how to reach themhi
we fin à few 'commands'  by using 
hacker's keyboard...
by ex ctrl z and y in order to change, and roll back
changes in text..

but nothing in order to save  changes or Format or...
???
is there some help? page? man?
where and how to reach them?
where are hiden commands and menus??
thanks for your help..
our mail togethres at gmail.com

thanks a lot and good luck !?
where are hiden commands and menus??
thanks for your help..
our mail togethres at gmail.com

thanks a lot and good luhi
we fin à few 'commands'  by using 
hacker's keyboard...
by ex ctrl z and y in order to change, and roll back
changes in text..

but nothing in order to save  changes or Format or...
???
is there some help? page? man?
where and how to reach themhi
we fin à few 'commands'  by using 
hacker's keyboard...
by ex ctrl z and y in order to change, and roll back
changes in text..

but nothing in order to save  changes or Format or...
???
is there some help? page? man?
where and how to reach them?
where are hiden commands and menus??
thanks for your help..
our mail togethres at gmail.com

thanks a lot and good luck !

**Comment by RohitKushvaha01** [comment]
> hi we find a few 'commands' by using hacker's keyboard... by ex ctrl z and y in order to change, and roll back changes in text..
> 
> but nothing in order to save changes or Format or... ??? is there some help? page? man? where and how to reach them? where are hiden commands and menus?? thanks for your help.. our mail : togethres at gmail.com
> 
> thanks a lot and good luck !

hey please create a issue about this and use a translater
