### ISSUE TITLE
Question: What happens with the plugin system?

### ISSUE THREAD

**Issue by Raffa064** [RohitKushvaha01/Xed-Editor#71]
Are you abandoning the plugins or are you going to reimplement them in another way?

From what I had seen in the implementation, I don't know if the way you were trying to do it would be possible, but I suggest that if you are going to implement it, using interpreted languages like lua, javascript, or even the java shell bean, would be easier than trying to directly access code from within another application... Once again, I don't know if it's possible to do it the way you were doing it, from what I know, I think Android doesn't allow it.

Scripting libraries I recommend:
- [Bean Shell](https://beanshell.github.io/)
- [RhinoJS](https://github.com/mozilla/rhino)
- [Luaj](https://github.com/luaj/luaj)

In case of using these libraries, you would just have to create an API for all the features that the plugins would have access to, and I believe that would be a much calmer task than trying to access code from other applications...

The plugins could be installed as a zip, or by its github repo url, like the neovim's plugins, I think that would be pretty cool.

**Comment by RohitKushvaha01** [comment]
> Are you abandoning the plugins or are you going to reimplement them in another way?
> 
> From what I had seen in the implementation, I don't know if the way you were trying to do it would be possible, but I suggest that if you are going to implement it, using interpreted languages like lua, javascript, or even the java shell bean, would be easier than trying to directly access code from within another application... Once again, I don't know if it's possible to do it the way you were doing it, from what I know, I think Android doesn't allow it.
> 
> Scripting libraries I recommend:
> - [Bean Shell](https://beanshell.github.io/)
> - [RhinoJS](https://github.com/mozilla/rhino)
> - [Luaj](https://github.com/luaj/luaj)
> 
> In case of using these libraries, you would just have to create an API for all the features that the plugins would have access to, and I believe that would be a much calmer task than trying to access code from other applications...
> 
> The plugins could be installed as a zip, or by its github repo url, like the neovim's plugins, I think that would be pretty cool.


Initially, I implemented a dynamic code execution system for plugins, which offered some significant advantages:

1. **Native Performance**: The plugins could run at full speed without the overhead of an interpreter.
2. **Maximum Control and Flexibility**: This approach allowed for deep integration and customization.

However, this method presented a major drawback: the complexity and difficulty of creating and maintaining plugins.

Subsequently, I transitioned to a JavaScript-based plugin system. While this simplified plugin development and provided a more accessible approach, I ultimately decided to discontinue it due to discouragement
