### ISSUE TITLE
html & markdown preview 

### ISSUE THREAD

**Issue by hasanelfalakiy** [RohitKushvaha01/Xed-Editor#90]
can you add preview for html & markdown?

**Comment by AndroMaster436** [comment]
The idea is good btw

**Comment by RohitKushvaha01** [comment]
> can you add preview for html & markdown?

Why not? 🙂

**Comment by AndroMaster436** [comment]
![Screenshot_20240821-214641~2](https://github.com/user-attachments/assets/239f6328-969c-4a78-88ec-fbcd8580b693)
There is a suggestion to make the file name display <title> instead. If the title is not in the code, then the file name

**Comment by hasanelfalakiy** [comment]
There is another suggestion, the preview display can be in desktop/mobile mode and can be zoomed in and zoomed out.

**Comment by AndroMaster436** [comment]
> There is another suggestion, the preview display can be in desktop/mobile mode and can be zoomed in and zoomed out.

And you also need a java script console. Then it will be ready.

**Comment by RohitKushvaha01** [comment]
> > There is another suggestion, the preview display can be in desktop/mobile mode and can be zoomed in and zoomed out.
> 
> And you also need a java script console. Then it will be ready.

This will be added in next commit but it will take week because I am busy with other things

![Screenshot_20240823-071325.jpg](https://github.com/user-attachments/assets/c04fca8f-adb9-4087-a713-d1ba40d93273)

![Screenshot_20240823-071347.jpg](https://github.com/user-attachments/assets/22aec5ce-cada-4a60-b384-1a90394994f8)

![Screenshot_20240823-071403.jpg](https://github.com/user-attachments/assets/978dab90-eb0f-423f-94cb-07808c880b73)
